services:
  mongodb:
    image: mongo:8.0
    restart: unless-stopped
    ports:
      - "27017:27017"
    volumes:
      - agilesprint-mongo:/data/db
  keycloak:
    image: quay.io/keycloak/keycloak:26.3
    command: start-dev --import-realm
    environment:
      KC_BOOTSTRAP_ADMIN_USERNAME: admin
      KC_BOOTSTRAP_ADMIN_PASSWORD: admin
    ports:
      - "8081:8080"
    volumes:
      - ./keycloak/realm-export.json:/opt/keycloak/data/import/realm-export.json:ro

volumes:
  agilesprint-mongo:
